type Package {
  language: String!
  category: String!
  name: String!
  git_repo: String!
  size: Int!
  size_format: String!
  size_compression: String
  logo: String
}

type Query {
  allPackages: [Package!]
}
